spring.application.name=vendas

# 1. URL do banco de dados (Variáveis de Ambiente para segurança)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vendas}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

# 4. Dialeto e inicialização
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 5. JWT
projeto.jwtSecret=${JWT_SECRET:chave_secreta_padrao_apenas_para_desenvolvimento_local}
projeto.jwtExpirationMs=900000