spring.application.name=vendas

spring.datasource.url = jdbc:postgresql://localhost:5432/controle-vendas

spring.datasource.username = postgres

spring.datasource.password = otavio01

spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


projeto.jwtSecret=bxOksa8BHgdAhR80Y3pEYvS5M+MnF2sheFDqprkTqQ4odqoszJLW1ikw64/nT/dTvlgrcBTq7HfK1B9Gai2h5A==

projeto.jwtExpirationMs = 900000